# Generated by Django 4.0.4 on 2022-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='poice_station',
            fields=[
                ('police_station_name', models.CharField(max_length=50)),
                ('police_station_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
