# Generated by Django 4.0.4 on 2022-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0002_poice_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='police_station',
            fields=[
                ('police_station_name', models.CharField(max_length=50)),
                ('police_station_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='poice_station',
        ),
    ]
