# Generated by Django 4.0.4 on 2022-11-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0003_police_station_delete_poice_station'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='my_user',
        ),
    ]
