# Generated by Django 4.0.4 on 2022-11-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0004_rename_user_my_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poice_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField(max_length=13)),
                ('Address', models.TextField()),
                ('password', models.CharField(max_length=16)),
                ('police_station_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.police_station')),
            ],
        ),
    ]
