# Generated by Django 4.0.4 on 2022-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0005_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='id',
        ),
        migrations.AlterField(
            model_name='police',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='police',
            name='poice_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
