# Generated by Django 4.0.4 on 2022-12-06 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0008_crime_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_category',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
