# Generated by Django 4.0.4 on 2022-12-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0009_crime_category_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='criminal',
            fields=[
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('prison', models.CharField(max_length=100)),
                ('court', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('photo', models.FileField(default=None, max_length=500, null=True, upload_to='media/')),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.crime_category')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.police_station')),
            ],
        ),
    ]
