# Generated by Django 4.0.4 on 2022-12-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0010_criminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIR_no', models.CharField(max_length=100)),
                ('accused_name', models.CharField(max_length=50)),
                ('applicant_name', models.CharField(max_length=50)),
                ('parentage', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('relation_with_accussed', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('fir_date', models.DateField()),
                ('final_status', models.DateField()),
                ('police_remark', models.TextField()),
                ('police_date', models.DateField()),
                ('section_of_law', models.CharField(max_length=100)),
                ('investigation_officer_name', models.CharField(max_length=100)),
                ('investigation_details', models.TextField()),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.crime_category')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.police_station')),
            ],
        ),
    ]
