# Generated by Django 4.0.4 on 2022-12-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0011_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='final_status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigation_details',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigation_officer_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='fir',
            name='police_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='fir',
            name='police_remark',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='fir',
            name='section_of_law',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
