# Generated by Django 4.2 on 2023-05-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0012_alter_fir_final_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='fir_date',
        ),
    ]
