# Generated by Django 4.2 on 2023-05-21 04:38

import crime_mgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0013_remove_fir_fir_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='fir_date',
            field=models.DateField(default=crime_mgmt.models.get_current_date),
        ),
    ]
