# Generated by Django 4.2 on 2023-05-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0014_fir_fir_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='final_status',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigation_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='investigation_officer_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='police_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='police_remark',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='section_of_law',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
