# Generated by Django 4.2 on 2023-05-21 05:32

import crime_mgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0016_alter_fir_final_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='police_date',
            field=models.DateField(default=crime_mgmt.models.get_current_date),
        ),
    ]
