# Generated by Django 4.2 on 2023-05-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0018_alter_fir_fir_no_alter_fir_accused_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='crime_type',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='police_station',
        ),
    ]
