# Generated by Django 4.2 on 2023-05-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime_mgmt', '0019_remove_fir_crime_type_remove_fir_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='crime_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.crime_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fir',
            name='police_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crime_mgmt.police_station'),
            preserve_default=False,
        ),
    ]
